posts/urls.py
from django.urls import path
from posts.views import *

app_name = 'posts'

urlpatterns = [
    path('', PostsFeedView.as_view(), name='blog'),
    path('posts/add/', AddPostView.as_view(), name='add_post'),
    path('posts/edit/<int:pk>',UpdatePostView.as_view(),name='edit_post'),
    path('posts/remove/<int:pk>/', DeletePostView.as_view(), name='delete_post'),
    path('posts/detail/<slug:url>/', PostDetailView.as_view(), name='detail'),
    path('posts/save_comment', save_comment, name='save_comment'),

]

simple_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('posts.urls')),
                  path('', include('users.urls')),
                  path('sobre-mi', TemplateView.as_view(template_name='about.html'), name='about')
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from django.views.generic import TemplateView
from users import views

app_name = 'users'

urlpatterns = [
    path('login/',views.LoginView.as_view(), name='login'),
    path('registro/',views.SignupView.as_view(),name='register'),
    path('logout/',views.auth_views.LogoutView.as_view(),name='logout'),
    path('registro_completado/',TemplateView.as_view(template_name='users/registerok.html'),name='registerok'),
]

categories/models.py
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=100,unique=True)

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.name

comments/models.py
from django.db import models
from django.contrib.auth.models import User
from posts.models import Post
from users.models import Profile


class Comment(models.Model):
    #Un usuario puede tener varios comentarios
    user = models.ForeignKey(User,on_delete=models.PROTECT)
    profile = models.ForeignKey(Profile,on_delete=models.PROTECT)
    post = models.ForeignKey(Post,on_delete=models.PROTECT)
    comment = models.CharField(max_length=5000)

    def __str__(self):
        return self.comment

posts/models.py
from django.db import models
from django.utils.text import slugify
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField
from categories.models import Category
from django.urls import reverse


class Post(models.Model):
    # ForeignKey - 1 a M
    user = models.ForeignKey(User, on_delete=models.PROTECT, verbose_name='Nombre de Usuario')
    profile = models.ForeignKey('users.Profile', on_delete=models.PROTECT)
    title = models.CharField(max_length=255, unique=True, verbose_name='Titulo')
    image_header = models.ImageField(upload_to='posts/photos', verbose_name='Imagen', blank=True)
    post = RichTextField
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    # ¿Es un borrador?
    is_draft = models.BooleanField(default=True)
    url = models.SlugField(max_length=255, unique=True, blank=True)
    views = models.PositiveIntegerField(default=0)
    # muchos a muchos
    categories = models.ManyToManyField(Category)

    class Meta:
        ordering = ('title',)

    def __str__(self):
        return '{} by @{}'.format(self.title, self.user.username)

    #Se requiere cuando se utiliza CreateView
    # def get_absolute_url(self):
    #     return reverse('posts:detail', args=(str(self.url)))

    def save(self, *args, **kwargs):
        self.url = slugify(self.title)
        super(Post, self).save(*args, **kwargs)

users/models.py
from django.contrib.auth.models import User
from django.db import models


class Profile(models.Model):
    # OneToOneField - Relación de uno a uno y PROTECT evitamos eliminar el usuario
    user = models.OneToOneField(User, on_delete=models.PROTECT)
    website = models.URLField(max_length=200, blank=True)
    photo = models.ImageField(upload_to='users/pictures', blank=True, null=True)
    data_modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        """Return username"""
        return self.user.username

comments/forms.py
from django import forms
from comments.models import Comment


class CreateCommentForm(forms.ModelForm):
    comment = forms.CharField(widget=forms.Textarea)

    class Meta:
        model = Comment
        fields = ('user', 'profile', 'post', 'comment')

users/forms.py
from django import forms
from django.contrib.auth.models import User
from users.models import Profile


class SignupForm(forms.Form):
    email = forms.CharField(min_length=6, max_length=70, widget=forms.EmailInput())
    username = forms.CharField(min_length=6, max_length=70, widget=forms.TextInput())
    password = forms.CharField(max_length=70, widget=forms.PasswordInput())
    password_confirmation = forms.CharField(max_length=70, widget=forms.PasswordInput())

    ''' Este método se utiliza para limpiar y validar campos que dependen unos de otros '''
    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get('password')
        password_confirmation = cleaned_data.get('password_confirmation')
        if password != password_confirmation:
            raise forms.ValidationError('Las contraseñas no coinciden.')
        return cleaned_data

    def save(self):
        data = self.cleaned_data
        '''Elimina password_confirmation'''
        data.pop('password_confirmation')
        user = User.objects.create_user(**data)
        ##CREA EL PERFIL, USER CREA EL USUARIO EN EL ADMIN DE DJANGO
        profile = Profile(user=user)
        profile.save()

posts/views.py
from django.shortcuts import redirect
from django.views.generic import DetailView, ListView, CreateView, UpdateView, DeleteView
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.urls import reverse_lazy
# Models
from posts.models import Post
from categories.models import Category
from comments.models import Comment
from comments.forms import CreateCommentForm


class PostsFeedView(ListView):
    template_name = 'posts/index.html'
    model = Post
    ordering = ('-created',)
    paginate_by = 5
    # Esto es lo que retorna
    context_object_name = 'posts'

    # Voy a retornar el listado siempre y cuando no se un borrador
    def get_queryset(self):
        return Post.objects.filter(is_draft=False)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        return context


# DetailView recupera información en concreto
class PostDetailView(DetailView):
    """Detail post."""
    template_name = 'posts/detail.html'
    model = Post
    context_object_name = 'post'
    slug_field = 'url'
    slug_url_kwarg = 'url'

    def get_queryset(self):
        return Post.objects.filter(is_draft=False)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        context['comments'] = Comment.objects.filter(post=self.get_object()).all()
        context['form_comments'] = CreateCommentForm()
        return context


class AddPostView(CreateView):
    template_name = 'posts/add.html'
    model = Post
    fields = '__all__'
    success_url = reverse_lazy('posts:blog')


class UpdatePostView(UpdateView):
    model = Post
    template_name = 'posts/update.html'
    fields = '__all__'


class DeletePostView(DeleteView):
    model = Post
    template_name = 'posts/delete.html'
    success_url = reverse_lazy('posts:blog')


@login_required
def save_comment(request):
    if request.method == 'POST':
        url = request.POST['url']
        post = {
            'user': request.user.id,
            'profile': request.user.id,
            'comment': request.POST['comment'],
            'post': request.POST['post']
        }
        form = CreateCommentForm(post)
        if form.is_valid():
            form.save()
            return redirect('posts:detail', url=url)
    else:
        return HttpResponse(status=405)
    return HttpResponse(status=500)

users/views.py
from django.views.generic import FormView
from django.urls import reverse_lazy
from django.contrib.auth import views as auth_views
from users.forms import SignupForm


# Una vista que muestra un formulario. En caso de error,
# vuelve a mostrar el formulario con errores de validación;
# en caso de éxito, redirige a una nueva URL.
class SignupView(FormView):
    template_name = 'users/register.html'
    form_class = SignupForm
    success_url = reverse_lazy('users:registerok')


class LoginView(auth_views.LoginView):
    template_name = 'users/login.html'

templates/about.html
{% extends "base.html" %}
{% block title %}Simple blog - Sobre mi{% endblock %}
{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-lg-8">
        <h1 class="mt-4">Sobre mi</h1>
        <hr>
        <img class="img-fluid rounded" src="https://via.placeholder.com/150x200/" alt="">
        <hr>
        <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus, vero, obcaecati, aut, error quam sapiente nemo saepe quibusdam sit excepturi nam quia corporis eligendi eos magni recusandae laborum minus inventore?</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ut, tenetur natus doloremque laborum quos iste ipsum rerum obcaecati impedit odit illo dolorum ab tempora nihil dicta earum fugiat. Temporibus, voluptatibus.</p>
        <hr>
      </div>
      </div>
    </div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}Simple blog{% endblock %}</title>
    {% load bootstrap4 %}
    {% bootstrap_css %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/blog-home.css' %}">
</head>
<body>
<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <a class="navbar-brand">Simple Blog</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'posts:blog' %}">Blog</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'about' %}">Sobre mi</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item">
                    <a class="nav-link" href="{% url 'posts:add_post' %}">Nuevo</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button"
                           aria-haspopup="true" aria-expanded="false">{{ request.user.username | capfirst }}</a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" href="{% url 'users:logout' %}">Logout</a>
                        </div>
                    </li>

                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:login' %}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:register' %}">Registro</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
<!-- Page Content -->
<div class="container">
    {% block content %}{% endblock %}
    <!-- Sidebar Widgets Column -->
    <div class="col-md-4">
        <!-- Categories Widget -->
        <div class="card my-4">
            <h5 class="card-header">Categorias</h5>
            <div class="card-body">
                <div class="row">
                    <div class="col-lg-12">
                        <ul class="list-unstyled mb-0">
                            {% for category in categories %}
                                <li>
                                    <a href="#">{{ category.name }}</a>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <!-- Side Widget -->
{#        <div class="card my-4">#}
{#            <h5 class="card-header">Side Widget</h5>#}
{#            <div class="card-body">#}
{#                You can put anything you want inside of these side widgets. They are easy to use, and feature the new#}
{#                Bootstrap 4 card containers!#}
{#            </div>#}
{#        </div>#}
    </div>
</div>
<!-- Footer -->
<footer class="py-5 bg-dark">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Simple Blog {% now "Y" %}</p>
    </div>
    <!-- /.container -->
</footer>
{% bootstrap_javascript jquery='full' %}
</body>
</html>

templates/posts/add.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <h1>Nuevo Post</h1>
    <form method="post" action="" class="mt-2" autocomplete="off" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form | crispy }}
        <button type="submit" class="btn btn-success">Crear post!</button>
    </form>
{% endblock %}

templates/posts/delete.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <br>
    <h3>Eliminando: {{ post.title }}</h3>
    <div class="form-group">
        <form method="post">
            {% csrf_token %}
            <strong> Desea continuar?</strong>
            <br>
            <button type="submit" class="btn btn-danger">Si, Eliminar
            </button>
        </form>
    </div>
{% endblock %}

templates/posts/detail.html
{% extends "base.html" %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                <h1 class="mt-4">{{ post.title }}</h1>
                <p class="lead">
                    por
                    <a href="#">{{ post.user.username }}</a>
                </p>
                <hr>
                <p>Escrito el {{ post.created }}</p>
                <hr>
                <img class="img-fluid rounded" src="{{ post.image_header.url }}" alt="">
                <hr>
                <p class="lead">{{ post.post|safe }}</p>
                <hr>
                {% if user.is_authenticated %}
                    <div class="card my-4">
                        <h5 class="card-header">Deja un comentario:</h5>
                        <div class="card-body">
                            <form method="POST" action='{% url "posts:save_comment" %}'>
                                {% csrf_token %}
                                <input type="hidden" name="url" value="{{ post.url }}"/>
                                <input type="hidden" name="post" value="{{ post.id }}"/>
                                <div class="form-group">
                                    <textarea class="form-control" name="comment" rows="3"></textarea>
                                </div>
                                <button type="submit" class="btn btn-primary">Enviar</button>
                            </form>
                        </div>
                    </div>
                {% endif %}
                <a href="{% url "posts:blog" %}" class="btn btn-success">Retroceder</a>
                <a href="{% url 'posts:delete_post' post.pk %}" class="btn btn-danger">Eliminar</a>

                {% for comment in comments %}
                    <div class="media mb-4">
                        {% if comment.user.profile.photo %}
                            <img class="d-flex mr-3 rounded-circle" width="50px" height="50px"
                                 src="/media/{{ comment.user.profile.photo }}" alt="">
                        {% else %}
                            <img class="d-flex mr-3 rounded-circle" src="https://via.placeholder.com/50x50/" alt="">
                        {% endif %}
                        <div class="media-body">
                            <h5 class="mt-0">{{ comment.user.username }}</h5>
                            {{ comment.comment }}
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

templates/posts/index.html
{% extends "base.html" %}
{% block content %}
    <div class="row">
        <div class="col-md-8">
            <h1 class="my-4">Posts
            </h1>
            {% for post in posts %}
                <div class="card mb-4">
                    <img class="card-img-top" src="{{ post.image_header.url }}" alt="Card image cap">
                    <div class="card-body">
                        <h2 class="card-title">{{ post.title }}</h2>
                        <!--            <p class="card-text">{{post.post|safe|truncatechars:300}}</p>-->
                        <a href="{% url 'posts:detail' post.url %}" class="btn btn-primary">Leer más &rarr;</a>
                        <a href="{% url 'posts:edit_post' post.pk %}" class="btn btn-primary">Editar</a>
                        <a href="{% url 'posts:delete_post' post.pk %}" class="btn btn-danger">Eliminar</a>
                    </div>
                    <div class="card-footer text-muted">
                        Escrito el {{ post.created }} - {{ post.user.username | capfirst }}
                    </div>
                </div>
            {% endfor %}
            <ul class="pagination justify-content-center mb-4">
                <li class="page-item">
                    <a class="page-link" href="#">&larr; Anterior</a>
                </li>
                <li class="page-item disabled">
                    <a class="page-link" href="#">Siguiente &rarr;</a>
                </li>
            </ul>
        </div>
    </div>
{% endblock %}

templates/posts/update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <h1>Editar Post</h1>
    <form method="post" action="" class="mt-2" autocomplete="off" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form | crispy }}
        <button type="submit" class="btn btn-secondary">Editar post!</button>
    </form>
{% endblock %}

templates/users/base.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}Simple blog - Login{% endblock %}</title>
    {% load bootstrap4 %}
    {% bootstrap_css %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/signin.css' %}">
</head>
<body class="text-center">
    {% block content %}{% endblock %}
    {% bootstrap_javascript jquery='full' %}
</body>
</html>

templates/users/login.html
{% extends "users/base.html" %}
{% block content %}
<form method="POST" action="{% url 'users:login' %}" class="form-signin">
    {% csrf_token %}
    <h1><a href="#" class="title-link">Simple Blog</a></h1>
    <h1 class="h3 mb-3 font-weight-normal">Login</h1>
    <label for="id_username" class="sr-only">Usuario</label>
    <input type="text" id="id_username" class="form-control" placeholder="Usuario" name="username" required autofocus>
    <label for="id_password" class="sr-only">Contraseña</label>
    <input type="password" id="id_password" class="form-control" placeholder="Contraseña" name="password" required>
    <div class="checkbox mb-3"></div>
    <button class="btn btn-lg btn-primary btn-block" type="submit">Login</button>
    {% if form.errors %}
        {% for field in form %}
            {% for error in field.errors %}
                <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endif %}
    <p class="mt-5 mb-3 text-muted">&copy; Simple Blog {% now "Y" %}</p>
    </form>
{% endblock %}

templates/users/register.html
{% extends "users/base.html" %}
{% block title %}Simple blog - Registro{% endblock %}
{% block content %}
<form class="form-signin" method="POST">
    {% csrf_token %}
    <h1><a href="#" class="title-link">Simple Blog</a></h1>
    <h1 class="h3 mb-3 font-weight-normal">Registro</h1>
    <label for="id_email" class="sr-only">Email</label>
    <input type="email" name="email" id="id_email" class="form-control" placeholder="Email" required autofocus>
    <label for="id_username" class="sr-only">Nombre de usuario</label>
    <input type="text" name="username" id="id_username" class="form-control" placeholder="Nombre de usuario" required>
    <label for="inputPassword" class="sr-only">Contraseña</label>
    <input type="password" name="password" id="id_password" class="form-control" placeholder="Contraseña" required>
    <label for="inputPassword" class="sr-only">Repetir contraseña</label>
    <input type="password" name="password_confirmation" id="id_password_confirmation" class="form-control" placeholder="Repetir contraseña" required>
    <div class="checkbox mb-3"></div>

    <button class="btn btn-lg btn-primary btn-block" type="submit">Registrarse</button>
    {% if form.errors %}
        {% for field in form %}
            {% for error in field.errors %}
                <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endif %}

    <p class="mt-5 mb-3 text-muted">&copy; Simple Blog {% now "Y" %}</p>
    </form>
{% endblock %}

templates/users/registerok.html
{% extends "users/base.html" %}
{% block title %}Simple blog - Registro completado{% endblock %}
{% block content %}
<main role="main" class="container">
   <div class="starter-template">
      <h1>Tu usuario ha sido creado con exito</h1>
      <p class="lead">Si la página no es redirigida en 5 segundos pulsa <a href="{% url 'users:login' %}">aquí</a></p>
   </div>
</main>
<script>
   setTimeout(function(){
       window.location.replace("{% url 'users:login' %}");
   }, 5000);
</script>
{% endblock %}